version: "3.9"

services:
  app:
    build: .
    container_name: user-management
    ports:
      - "8081:8081"
    restart: always
    environment:
      JWT_PUBLIC_KEY_PATH: /app/keys/public_key.pem
      INSOMNIA_COLLECTION_PATH: /app/collections/insomnia-collection.yaml
      POSTMAN_COLLECTION_PATH: /app/collections/postman-collection.json
      HOST_DB: postgres_user_db
    volumes:
      - ./keys:/app/keys
      - ./collections:/app/collections
