spring:
  mvc:
    static-path-pattern: /static/**
  application:
    name: ms-user
  datasource:
    url: jdbc:postgresql://${HOST_DB:localhost}:5432/user_db?currentSchema=management
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  rabbitmq:
    publisher-returns: true
    publisher-confirm-type: correlated
    host: ${HOST_RABBIT:localhost}
    port: 5672
    username: guest
    password: guest
    connection-timeout: 5000
    template:
      retry:
        enabled: false
        max-attempts: 3
        initial-interval: 1000
        multiplier: 2
        max-interval: 10000

amqp:
  queue:
    user-created: user-created.queue
    notify-user: notify-user.queue
  dlq:
    user-created-dlq: user-created.dlq
    notify-user-dlq: notify-user.dlq

server:
  servlet:
    context-path: /api/v1
  port: 8081

jwt:
  public-key-path: ${JWT_PUBLIC_KEY_PATH:./keys/public_key.pem}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always


app:
  collection:
    path:
      insomnia: ${INSOMNIA_COLLECTION_PATH:./collections/insomnia-collection.yaml}
      postman: ${POSTMAN_COLLECTION_PATH:./collections/postman-collection.json}
